# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-04 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('preauth', 'Preauth'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input'), ('paid', 'Paid')], default='waiting', max_length=10, verbose_name='Status'),
        ),
    ]
