from django.utils.translation import ugettext_lazy as _

__all__ = (
    'PAYMENT_STATUS_WAITING',
    'PAYMENT_STATUS_PREAUTH',
    'PAYMENT_STATUS_CONFIRMED',
    'PAYMENT_STATUS_REJECTED',
    'PAYMENT_STATUS_REFUNDED',
    'PAYMENT_STATUS_ERROR',
    'PAYMENT_STATUS_INPUT',
    'PAYMENT_STATUSES',
    'PAYMENT_STATUS_CHOICES',
    'DEFAULT_PAYMENT_STATUS',
    'PAYMENT_STATUS_PAID'
)

PAYMENT_STATUS_WAITING = 'waiting'
PAYMENT_STATUS_PREAUTH = 'preauth'
PAYMENT_STATUS_CONFIRMED = 'confirmed'
PAYMENT_STATUS_REJECTED = 'rejected'
PAYMENT_STATUS_REFUNDED = 'refunded'
PAYMENT_STATUS_ERROR = 'error'
PAYMENT_STATUS_INPUT = 'input'
PAYMENT_STATUS_PAID = 'paid'
DEFAULT_PAYMENT_STATUS = PAYMENT_STATUS_WAITING

PAYMENT_STATUSES = {
    PAYMENT_STATUS_WAITING: _("Waiting"),
    PAYMENT_STATUS_PREAUTH: _("Preauth"),
    PAYMENT_STATUS_CONFIRMED: _("Confirmed"),
    PAYMENT_STATUS_REJECTED: _("Rejected"),
    PAYMENT_STATUS_REFUNDED: _("Refunded"),
    PAYMENT_STATUS_ERROR: _("Error"),
    PAYMENT_STATUS_INPUT: _("Input"),
    PAYMENT_STATUS_PAID: _("Paid")

}

PAYMENT_STATUS_CHOICES = list(PAYMENT_STATUSES.items())
