# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations_addons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='group',
            new_name='user_group',
        ),
    ]
