from __future__ import unicode_literals

CITY_REPLACE = {
    'Abydos (?)': 'Abydos',
    'Abydos (?) of Koptos': 'Abydos',
    'Abydos?': 'Abydos',
    'Akhmim (?)': 'Akhmim',
    'Alexandrië (?)': 'Alexandrië',
    'Amarna ; Thebe': 'Amarna',
    'Assiut (?)': 'Assiut',
    'Bubastis (?)': 'Bubastis',
    'Bubastis ; Tell Basta': 'Bubastis',
    'Chozam (?)': 'Chozam',
    'Dahshur (?)': 'Dahshur',
    'Dakkeh ; Elephantine': 'Dakkeh',
    'Deir el-Bersha (?)': 'Deir el-Bersha',
    'Delta (?)': 'Delta',
    'Gebel Atolna ; Suez': 'Gebel Atolna',
    'Gebelein (?)': 'Gebelein',
    'Giza (?)': 'Giza',
    'Giza ; Rifa': 'Giza',
    'Giza, Kafr el-Gebel': 'Giza',
    'Helwan (?)': 'Helwan',
    'Hermopolis ; Tuna el-Gebel': 'Hermonthis',
    'Hermopolis; Tuna el-Gebel': 'Hermonthis',
    'Hierakonpolis (?)': 'Hierakonpolis',
    'Kalabsha (?)': 'Kalabsha',
    'Kalabsha (?), Egypte, Afrika': 'Kalabsha',
    'Leontopolis ; Tell el-Muqdam': 'Leontopolis',
    'Malqata; Thebe': 'Malqata',
    'Marea ; Alexandrië (?)': 'Marea',
    'Medinet Habu; Thebe': 'Medinet Habu',
    'Meir (?)': 'Meir',
    'Memphis (?)': 'Memphis',
    'Mendes (?)': 'Mendes',
    'Nagada (?)': 'Nagada',
    'Praeneste?': 'Praeneste',
    'Qantir (?)': 'Qantir',
    'Sakkara (?)': 'Sakkara',
    'Sakkara (?) of el-Hibeh (?)': 'Sakkara',
    'Sanam, graf 0195': 'Sanam',
    'Saqqara (?)': 'Saqqara',
    'Saqqara, graf van Horemheb (?)': 'Saqqara',
    'Saqqara-noord': 'Saqqara',
    'Saqqara; graf ST 211': 'Saqqara',
    'Sheikh Ibada ; Antinoe': 'Sheikh Ibada',
    'Sheikh Ibada; Antinoe': 'Sheikh Ibada',
    'Shokan ; Abu Simbel': 'Shokan',
    'Syene; Aswan': 'Syene',
    'Tebtunis (?)': 'Tebtunis',
    'Tehneh (?)': 'Tehneh',
    'Tell el-Roba ; Mendes': 'Tell el-Roba',
    'Thebe (?)': 'Thebe',
    'Thebe ; Deir el-Bahari': 'Thebe',
    'Thebe ; Deir el-Medina': 'Thebe',
    "Thebe ; Dra Abu 'n-Naga": 'Thebe',
    'Thebe ; Sheikh Abd-el-Qurna': 'Thebe',
    'Tuna el-Gebel (?)': 'Tuna el-Gebel',
    'Zawiyet al-Aryan (?)': 'Zawiyet al-Aryan',
    'el-Araba (? ); Abydos (?)': "el-Araba",
    'el-Balyana (?)': 'el-Balyana',
    'el-Behnasa (?); Oxyrhynchus (?)': 'el-Behnasa',
    'el-Behnasa ; Oxyrhynchus': 'el-Behnasa',
    'el-Behnasa ; Oxyrhynchus; Osireion': 'el-Behnasa',
    'el-Behnasa; Oxyrhynchus': 'el-Behnasa',
}

CITY_MAPPING = {
    'Abdallah Nirqi',
    'Abu Roash',
    'Abusir',
    'Abydos',
    'Achmim',
    'Adria',
    'Akhmim',
    'Alexandrië',
    'Amarna',
    'Amsterdam',
    'Aniba',
    'Antaeopolis',
    'Arab el-Borg',
    'Armant',
    'Arsinoë',
    'Assiut',
    'Aswan',
    'Athene',
    'Bawit',
    'Benha',
    'Beni Hassan',
    'Bet Khallaf',
    'Bubastis',
    'Cairo',
    'Chozam',
    'Cortona',
    'Cyprus',
    'Dahshur',
    'Dakkeh',
    'Deir el-Bahri',
    'Deir el-Bersha',
    'Deir el-Medina',
    'Delta',
    'Diospolis Magna',
    'Elephantine',
    'Faras',
    'Gebel Atolna ; Suez',
    'Gebelein',
    'Giza',
    'Hawara',
    'Heliopolis',
    'Helwan',
    'Hermonthis',
    'Hierakonpolis',
    'Kalabsha',
    'Karnak',
    'Khargeh Oase',
    'Kom Abu Billu',
    'Kom el Ahmar (Minufia)',
    'Koptos',
    'Leiden',
    'Leontopolis ; Tell el-Muqdam',
    'Malqata; Thebe',
    'Manchester',
    'Marea',
    'Medinet Habu',
    'Meidum',
    'Meir',
    'Memphis',
    'Mendes',
    'Meroë',
    "Nag' ed-Deir",
    'Nagada',
    'Napata',
    'Nijmegen',
    'Nistelrode',
    'Nubië',
    'Nuri',
    'Oud-Wulven',
    'Oxyrhynchus',
    'Parijs',
    'Persepolis',
    'Philae',
    'Phoenicië',
    'Praeneste',
    'Qantir',
    'Qasr Ibrim',
    'Rifa',
    'Rijkevoort',
    'Rizeiqat',
    'Rossum',
    'Sakkara',
    'Sanam',
    'Saqqara',
    'Saïs',
    'Serabit el-Khadim',
    'Sheikh Ibada',
    'Shokan',
    'Sjeich Abd-el-Qurna',
    'Stevensweert',
    'Syene',
    'Taffeh',
    'Tanis',
    'Tarkhan',
    'Tebtunis',
    'Tehneh',
    'Tell Balata',
    'Tell el-Roba',
    'Tell-Firaun',
    'Teshlot',
    'Testour',
    'Thebe',
    'Tod',
    'Tuna el-Gebel',
    'Tunis',
    'Venlo',
    'Vulci',
    'Wassenaar',
    'Zawiyet al-Aryan',
    'el-Araba',
    'el-Balyana',
    'el-Behnasa',
    'el-Mahasna',
    'er-Rubayat',
}

PERIOD_MAPPING = {
    'greco-roman period': 'Graeco-Roman Period',
    'old empire': 'Old Kingdom',
    'middle empire': 'Middle Kingdom',
    'new empire': 'New Kingdom',
    'neolithic': 'Neolithic Period',
    'ptolema time': 'Ptolemaic Period',
    'ptolemae time': 'Ptolemaic Period',
    'ptolemic time': 'Ptolemaic Period',
    'prehistory': 'Prehistoric Period',
    'constantine': 'Constantine The Great',
    'amenhotep II': 'Amenhotep II Aakheperure',
    'first intermediate period': '1st Intermediate Period',
    'second intermediate period': '2nd Intermediate Period',
    'third intermediate period': '3rd Intermediate Period',
    'roman imperial time': 'Roman Period',
    'roman imperial times': 'Roman Period',
    'roman imperial age': 'Roman Period',
    'roman': 'Roman Period',
    'dynastic period': 'Early Dynastic Period_Thinite Period',
    'early dynastic period': 'Early Dynastic Period_Thinite Period',
    'archaic period': 'Early Dynastic Period_Thinite Period',
    'amarna': 'Amenhotep IV / Akhenaten Neferkheperure',
    'amarna period': 'Amenhotep IV / Akhenaten Neferkheperure',
    'amarna-periode': 'Amenhotep IV / Akhenaten Neferkheperure',
    'amarnaperiode': 'Amenhotep IV / Akhenaten Neferkheperure',
    'prehistoric': 'prehistoric period',
    'saitic period': '26th Dynasty',
    'saite period': '26th Dynasty',
    'arab period': 'Islamic Period',
    'arabic period': 'Islamic Period'
}

THEBES_COORDINATES = {
    'thebe': (25.6760290667, 32.6339435),
    'thebes': (25.6760290667, 32.6339435),
    'amama': (25.6760290667, 32.6339435),
    'asasif': (25.7342620573, 32.6114541611),
    'deir el-bahari': (25.738333, 32.607778),
    'deir el-bahri': (25.738333, 32.607778),
    'deir el medina': (25.728284, 32.601357),
    'deir el medineh': (25.728284, 32.601357),
    'deir el-medina': (25.728284, 32.601357),
    "dra abu 'n-naga": (25.7358897, 32.6181205),
    'medinet habu': (25.7200144111, 32.5998824787),
    'kamak': (25.6886038, 32.64100155),
    'shokan': (26.31047, 30.110894),
    'valley of the kings': (25.7378571, 32.6007001),
    'leontopolis': (30.683333, 31.35),
}

MET_OBJECT_TYPE_EN_WHITELIST = set(
    [
        'Scarab',
        'Amulet',
        'Jar Label',
        'Relief fragment',
        'Shabti',
        'Relief',
        'Sealing',
        'Jar',
        'Inlay',
        'Pendant',
        'Beads',
        'Facsimile',
        'Tile',
        'Bead',
        'Statuette',
        'Ring',
        'Cone',
        'Ostracon',
        'string',
        'Mold',
        'Necklace',
        'worker',
        'Tool',
        'Vase fragment',
        'Bowl',
        'Figurine',
        'Sarcophagus fragment',
        'Plaque',
        'Worker Shabti',
        'circular impression',
        'hieratic',
        'Seal',
        'Coin',
        'Statue',
        'Wedjat eye',
        'Jar label',
        'Linen',
        'Game piece',
        'Head',
        'Cast',
        'hieroglyph',
        'Punt reliefs',
        'Talatat',
        'cartouche',
        'Vase',
        'beads',
        'Ornament',
        'Papyrus',
        'Stela',
        'Earring',
        'Blade',
        'Bracelet',
        'Vessel fragment',
        'Cylinder seal',
        'Coffin',
        'Canopic jar',
        'figure',
        'Ring fragment',
        'scarab',
        'tablet',
        'Food',
        'Weight',
        'Linen fragment',
        'Kohl jar',
        'Mummy Cloth Fragment',
        'hieroglyphs',
        'Knife',
        'Fragment',
        'Scaraboid',
        'Linen mark',
        'Palette',
        'Arrowhead',
        'Cowroid',
        'Glass',
        'Dish',
        'Music',
        'amulet',
        'ankh',
        'Sealing fragment',
        'Bottle',
        'Model',
        'Gold and Silver',
        'Ointment jar',
        'Votive',
        'Cup',
        'plaque',
        'Canopic box',
        'Linen Mark',
        'Mask',
        'Sheet',
        'Tile fragment',
        'Vessel',
        'Arrow',
        'Inlay fragment',
        'Model vase',
        'Chalice',
        'Linen sheet',
        'Jug',
        'sickle',
        'Brick',
        'Flint',
        'bezel',
        'lid',
        'animal part',
        'papyrus',
        'Anklet',
        'Basket',
        'Scraper',
        'Arrow point',
        'Book of the Dead',
        'Heart Scarab',
        'Canopic chest',
        'Hair pin',
        'relief',
        'shell',
        'Bandage',
        'Headrest',
        'Votive bracelet',
        'cup',
        'Earrings',
        'Bowl fragment',
        'Chisel',
        'Jar Fragment',
        'amulets',
        'Comb',
        'Finger stall',
        'jar',
        'Coffin Inlay',
        'Fish hook',
        'Spear',
        'bead',
        'Box',
        'Glass fragment',
        'Kohl tube',
        'Amulet plaque',
        'Djed pillar',
        'Mummy',
        'Staff',
        'Toe stall',
        'Fish net weight',
        'Reel',
        'Shell',
        'Amulet pendant',
        'Kohl stick',
        'Mallet',
        'Mirror',
        'Bead plaque',
        'Bust',
        'Coffin fragment',
        'Fragments',
        'Offering table',
        'Canopic jar lid',
        'Grinding stone',
        'Lamp',
        'Pot',
        'Seal amulet',
        'Stamp seal',
        'ring',
        'signet',
        'Funerary figure',
        'Shabti box',
        'Weaving',
        'seal',
        'wedjat eye',
        'Canopic Jar',
        'Mummy cloth',
        'Tweezers',
        'Ball',
        'Beaker',
        'Bow',
        'Clasp',
        'Needle',
        'Razor',
        'Kohl Tube',
        'Seal plaque',
        'arrowhead',
        'mosaic',
        'Sarcophagus',
        'vase',
        'Cippus',
        'Flask',
    ]
)

MET_OBJECT_TYPE_NL_WHITELIST = set(
    [
        'Scarabee',
        'Amulet',
        'Vaasetiket',
        'Reliëf fragment',
        'Oesjabti',
        'Reliëf',
        'Afdichting',
        'Kruik',
        'Inlegwerk',
        'Hanger',
        'Beads',
        'facsimile',
        'Tegel',
        'Kraal',
        'Beeldje',
        'Ring',
        'Kegel',
        'Ostracon',
        'draad',
        'Gietvorm',
        'Halssnoer',
        'arbeider',
        'gereedschap',
        'Vaas fragment',
        'Kom',
        'Figuurtje',
        'Sarcofaag fragment',
        'gedenkplaat',
        'Werknemer Oesjabti',
        'ronde indruk',
        'hiërarchisch',
        'Zegel',
        'Munt',
        'Beeld',
        'Wedjat oog',
        'Vaasetiket',
        'Linnen',
        'Pion',
        'Hoofd',
        'Gegoten',
        'hiëroglief',
        'Puntreliëfs',
        'Talatat',
        'cartouche',
        'Vaas',
        'kralen',
        'Ornament',
        'Papyrus',
        'Stèle',
        'Oorring',
        'Lemmet',
        'Armband',
        'Vatfragment',
        'Cilinder zegel',
        'Kist',
        'Canopenvaas',
        'figuur',
        'Ring fragment',
        'Scarabee',
        'tablet',
        'Voedsel',
        'Gewicht',
        'Linnen fragment',
        'Kool kruik',
        'Mummie doek Fragment',
        'hiërogliefen',
        'Mes',
        'Fragment',
        'Scarabee-achtig voorwerp',
        'Linnen merk',
        'Palet',
        'Pijlpunt',
        'Cowroid',
        'Glas',
        'Bord',
        'Muziek',
        'Amulet',
        'ankh',
        'Afdichtingsfragment',
        'Fles',
        'Model',
        'Goud en Zilver',
        'Zalf kruik',
        'Votief',
        'Beker',
        'gedenkplaat',
        'Canopenkist',
        'Linnen Mark',
        'Masker',
        'Vel',
        'Tegel fragment',
        'Vaartuig',
        'Pijl',
        'Inlegwerk fragment',
        'Model vaas',
        'Kelk',
        'Linnen lakens',
        'Kan',
        'Sikkel',
        'Baksteen',
        'Vuursteen',
        'schuine kant',
        'deksel',
        'dierlijk deel',
        'Papyrus',
        'Enkelring',
        'Korf',
        'Schrapper',
        'Pijlpunt',
        'Dodenboek',
        'Hart Scarabee',
        'Canopenkoffer',
        'Haar pin',
        'Reliëf',
        'Schelp',
        'Verband',
        'hoofdsteun',
        'Votive armband',
        'Beker',
        'oorbellen',
        'Kom fragment',
        'Beitel',
        'Kruik Fragment',
        'amuletten',
        'Kam',
        'Vingerkraam',
        'Kruik',
        'Coffin Inlegwerk',
        'Vis haak',
        'Speer',
        'kraal',
        'Palm',
        'Glas fragment',
        'Kooltube',
        'Amulet plaque',
        'Djed pijler',
        'mummie',
        'Staf',
        'Toe stall',
        'Vis net gewicht',
        'Haspel',
        'Schelp',
        'Amulet hanger',
        'Koolstok',
        'Hamer',
        'Spiegel',
        'Bead plaque',
        'Buste',
        'Doodskistfragment',
        'fragmenten',
        'Offertafel',
        'Canopenvaas deksel',
        'Slijpen gesteente',
        'Lamp',
        'Pot',
        'Zegel amulet',
        'Stempel zegel',
        'ring',
        'zegel',
        'Funerair figuur',
        'Oesjabikist',
        'het weven',
        'Zegel',
        'wedjat oog',
        'Canopenvaas',
        'Mummie doek',
        'Tang',
        'Bal',
        'Beker',
        'Boog',
        'Sluiting',
        'Naald',
        'Scheermes',
        'Kooltube',
        'Zegel plaque',
        'pijlpunt',
        'mozaïek',
        'Sarcofaag',
        'Vaas',
        'Cippus',
        'Flacon',
    ]
)

MET_MATERIAL_EN_WHITELIST = [
    'material',
    'man made material',
    'anhydrite',
    'faience',
    'gesso',
    'glass',
    'glaze',
    'incense',
    'mortar',
    'plaster',
    'pottery',
    'terracotta',
    'reed',
    'non organic',
    'alloys',
    'brass',
    'bronze',
    'electrum',
    'unspecified alloys',
    'metal',
    'antimony',
    'copper',
    'gold',
    'iron',
    'lead',
    'platinum',
    'silver',
    'tin',
    'unspecified metal',
    'mineral',
    'agate',
    'amazonite',
    'amethyst',
    'anhydrite',
    'beryl',
    'carnelian',
    'chalcedony',
    'chrysoprase',
    'emery',
    'felspar',
    'fluorite',
    'galena',
    'garnet',
    'graphite',
    'gypsum',
    'jade',
    'jadeite',
    'lapis lazuli',
    'malachite',
    'mica',
    'microcline',
    'green feldspar',
    'amazon-stone',
    'nephrite',
    'olivinemi',
    'onyx',
    'orpiment',
    'peridot',
    'quartz',
    'rock crystal',
    'red ochre',
    'salt',
    'sardonyx',
    'sulphur',
    'turquoise',
    'unspecified mineral',
    'yellow ochre',
    'natural compound',
    'nile mud',
    'alum',
    'chrysocolla',
    'clay',
    'sand',
    'unspecified natural compounds',
    'stone',
    'iceland spar',
    'anorthosite',
    'basalt',
    'breccia',
    'calcite',
    'diorite',
    'dolerite',
    'dolomite',
    'flint',
    'chert',
    'gabbro',
    'granite',
    'granodiorite',
    'greywacke',
    'jasper',
    'limestone',
    'marble',
    'mudstone',
    'obsidian',
    'porphyry',
    'quartzite',
    'sandstone',
    'serpentinite',
    'silicified wood',
    'siltstone',
    'slate',
    'steatite',
    'soap stone',
    'syenite',
    'unspecified rock',
    'volcanic ash',
    'tuff',
    'organic',
    'animal product',
    'beeswax',
    'bone',
    'claw',
    'eggshell',
    'ostrich eggshell',
    'fat',
    'feather',
    'glue',
    'gut',
    'hair',
    'horn',
    'ivory',
    'elephant ivory',
    'hippopotamus ivory',
    'leather',
    'mother of pearl',
    'parchment',
    'pearl',
    'shell',
    'shell (marine)',
    'shell (nile)',
    'tortoise shell',
    'unspecified plant product',
    'ashes',
    'charcoal',
    'fiber (from plants and animals)',
    'cotton',
    'date-palm fiber',
    'flax',
    'halfa grass',
    'hemp',
    'papyrus',
    'rush',
    'silk',
    'unspecified fiber',
    'wool',
    'hydrocarbon',
    'bitumen',
    'coal',
    'plant product',
    'frankincense',
    'gum arabic',
    'myrrh',
    'oil',
    'resin',
    'straw',
    'wood',
    'christ thorn',
    'acacia',
    'almond',
    'ash',
    'beech',
    'birch',
    'box',
    'carob',
    'cedar',
    'cypress',
    'date palm',
    'dom palm',
    'ebony',
    'elm',
    'fir',
    'hornbeam',
    'juniper',
    'lime',
    'liquidambar',
    'oak',
    'persea',
    'pine',
    'sycamore',
    'tamarisk',
    'unspecified wood',
    'willow',
    'yew'
]

MET_MATERIAL_NL_WHITELIST = [
    'materiaal',
    'materiaal vervaardigd door de mens',
    'anhydriet',
    'faience',
    'gesso',
    'glas',
    'glazuur',
    'wierook',
    'mortel',
    'pleister',
    'aardewerk',
    'terracotta',
    'riet',
    'niet-organisch',
    'legering',
    'messing',
    'brons',
    'electrum',
    'ongespecificeerde legeringen',
    'metaal',
    'antimoniun',
    'koper',
    'goud',
    'ijzer',
    'lood',
    'platinum',
    'zilver',
    'tin',
    'ongespecificeerd metaal',
    'mineraal',
    'agaat',
    'amazoniet',
    'amethist',
    'anhydriet',
    'beryl',
    'cornalijn',
    'chalcedon',
    'chrysopraas',
    'amaril',
    'veldspaat',
    'fluoriet',
    'loodglans',
    'granaat',
    'grafiet',
    'gips',
    'jade',
    'jadeïet',
    'lapis-lazuli',
    'malachiet',
    'mica',
    'microcliet',
    'groene veldspaat',
    'amazonesteen',
    'nefriet',
    'olivien',
    'onyx',
    'orpiment',
    'operment',
    'peridoot',
    'kwarts',
    'rotskristal',
    'hematiet',
    'zout',
    'sardonyx',
    'sulfer',
    'turkoois',
    'ongespecificeerd mineraal',
    'limoniet',
    'natuurlijke samenstelling',
    'leem van de nijl',
    'aluin',
    'chrysocolla',
    'klei',
    'zand',
    'ongespecificeerde natuurlijke samenstelling',
    'gesteente',
    'ijslandse spaat',
    'anorthosiet',
    'basalt',
    'breccia',
    'calciet',
    'albast',
    'dioriet',
    'doleriet',
    'dolomiet',
    'kleisteen-hoornsteen',
    'gabbro',
    'graniet',
    'granodioriet',
    'grauwak',
    'jaspis',
    'kalksteen',
    'marmer',
    'leem',
    'obsidiaan',
    'porfier',
    'kwartsiet',
    'zandsteen',
    'serpentijn',
    'versteend hout',
    'slib',
    'leisteen',
    'steatiet',
    'syeniet',
    'ongespecificeerd gesteente',
    'vulkanische as',
    'tufsteen',
    'organisch',
    'dierlijk product',
    'bijenwas',
    'gebeente',
    'klauw',
    'eierschaal',
    'schelp van een struisvogelei',
    'vet',
    'pluim',
    'kleefstof',
    'darm',
    'haar',
    'hoorn',
    'ivoor',
    'olifantenivoor',
    'nijlpaardenivoor',
    'leer',
    'parelmoer',
    'perkament',
    'parel',
    'schelp',
    'zeeschelp',
    'nijlschelp',
    'schildpadschelp',
    'ongespecificeerd plantproduct',
    'as',
    'houtskool',
    'plant- en diervezel',
    'katoen',
    'dadelpalmvezel',
    'vlas',
    'halfa-gras',
    'hennep',
    'papyrus',
    'bies',
    'zijde',
    'ongespecificeerde vezel',
    'wol',
    'koolwaterstof',
    'bitumen',
    'kool',
    'plantproduct',
    'wierook',
    'arabische gom',
    'myrre',
    'olie',
    'hars',
    'stro',
    'hout',
    'doorn',
    'acacia',
    'amandel',
    'es',
    'beuk',
    'berk',
    'palm',
    'johannesboom',
    'ceder',
    'cypres',
    'dadelpalm',
    'doempalm',
    'ebbehout',
    'olm',
    'dennehout',
    'haagbeuk',
    'jeneverbesstruik',
    'linde',
    'amberboom',
    'eik',
    'persea',
    'pijnboom',
    'sycomore',
    'tamarisk',
    'ongespecificeerd hout',
    'wilg',
    'taxus'
]

MISSING_COUNTRIES = {
    'abu zaidan': 'Bahrain',
    'abusir': 'Egypt',
    'ahnas (ehnasya)': 'Egypt',
    'al-jizah': 'Jordan',
    'al-qahirah': 'Egypt',
    'araba al-madfuna': 'Egypt',
    'asasif': 'Egypt',
    'aswan': 'Egypt',
    'asyut': 'Egypt',
    'attikí': 'Greece',
    'az-zaqaziq': 'Egypt',
    'behbeit el higra': 'Egypt',
    'benha': 'Egypt',
    'bruxelles': 'Belgium',
    'casalmaggiore': 'Italy',
    'deir el-bahri, thebes': 'Egypt',
    'dendera': 'Egypt',
    'dinslaken': 'Germany',
    'el-manshah (ptolemais hermiou)': 'Egypt',
    'esna': 'Egypt',
    'gebelein': 'Egypt',
    'herakleopolis magna': 'Egypt',
    'hermopolis': 'Egypt',
    'lisht': 'Egypt',
    "ma'mariya": 'Egypt',
    'mendes': 'Egypt',
    'mezaideh': 'Egypt',
    'mir': 'Egypt',
    'mitrahina': 'Egypt',
    'moskva': 'Russia',
    'naga ed-deir': 'Egypt',
    'saint-claude': 'France',
    'sakkara': 'Egypt',
    'san al-hajar al-qibliyah': 'Egypt',
    'saqqâra': 'Egypt',
    'sawhaj': 'Egypt',
    'schrobenhausen': 'Germany',
    'shedet': 'Egypt',
    'sumenu (modern day dahamsha)': 'Egypt',
    'taicang': 'China',
    'tell el muqdam (leontopolis)': 'Egypt',
    'tell el-yahudiya': 'Egypt',
    'terenouthis': 'Egypt',
    'thebes (deir el medina)': 'Egypt',
    'thebes (necropolis)': 'Egypt',
    'thebes, malkata': 'Egypt',
    'türkiye': 'Turkey',
    'îran': 'Iran'
}

OBJECT_TYPE_SYNONYMS_EN = {
    '"tell basta treasure"': 'Do not use',
    '(not assigned)': 'Do not use',
    'accessories': 'Accessory',
    'accessory': 'Accessory',
    'aes-24': 'Do not use',
    'aes-33': 'Do not use',
    'ahmose': 'Do not use',
    'ahmose-nefertari': 'Do not use',
    'akhenaten': 'Do not use',
    'amasis': 'Do not use',
    'amduat': 'Amduat',
    'amenemhat': 'Do not use',
    'amenemhat i': 'Do not use',
    'amenemhat iii': 'Do not use',
    'amenhotep': 'Do not use',
    'amenhotep i': 'Do not use',
    'amenhotep ii': 'Do not use',
    'amenhotep iii': 'Do not use',
    'amphora': 'Amphora',
    'amulet': 'Amulet',
    'amulet pendant': 'Pendant',
    'amulet plaque': 'Plaque',
    'amulet-pendant': 'Pendant',
    'amulet-pendants': 'Pendant',
    'amulets': 'Amulet',
    'amun': 'Do not use',
    'amun-re': 'Do not use',
    'animal': 'Animal',
    'ankh': 'Do not use',
    'anklet': 'Anklet',
    'anubis': 'Do not use',
    'ape amulet': 'Amulet',
    'apries': 'Apries',
    'architectural element': 'Architectural element',
    'arm': 'Arm',
    'arms and armor': 'Arms and armor',
    'arrow': 'Arrow',
    'arrow head': 'Arrow head',
    'arrowhead': 'Arrowhead',
    'aten cartouche': 'Do not use',
    'aten cartouches': 'Do not use',
    'ax': 'Ax',
    'baboon': 'Baboon',
    'ball': 'Ball',
    'bandage': 'Bandage',
    'basket': 'Basket',
    'bastet': 'Do not use',
    'bat': 'Bat',
    'bead': 'Bead',
    'bead plaque': 'Bead',
    'beads': 'Bead',
    'beaker': 'Beaker',
    'bes': 'Do not use',
    'bird': 'Bird',
    'body part': 'Body part',
    'book of the dead': 'Book of the dead',
    'bottle': 'Bottle',
    'bow': 'Bow',
    'bowl': 'Bowl',
    'bowl fragment': 'Bowl',
    'box': 'Box',
    'bracelet': 'Bracelet',
    'bracelet (bangle)': 'Bracelet',
    'brick': 'Brick',
    'broad collar': 'Collar',
    'bronze': 'Do not use',
    'bull': 'Bull',
    'bust': 'Bust',
    'button seal': 'Button seal',
    "calf's head": "Calf's head",
    'canope': 'Canope',
    'canopic box': 'Canopic box',
    'canopic chest': 'Canopic box',
    'canopic jar': 'Canopic jar',
    'canopic jar lid': 'Canopic jar',
    'cartonnage': 'Cartonnage',
    'cartouche': 'Cartouche',
    'casting': 'Casting',
    'cat': 'Cat',
    'cattle': 'Do not use',
    'ceramics': 'Ceramic',
    'chalice': 'Chalice',
    'child': 'Child',
    'chisel': 'Chisel',
    'circular': 'Do not use',
    'circular impression': 'Impression',
    'clapper': 'Clapper',
    'clasp': 'Clasp',
    'clavus': 'Do not use',
    'coffin': 'Coffin',
    'coffin inlay': 'Inlay',
    'coin': 'Coin',
    'coinage': 'Coin',
    'comb': 'Comb',
    'cone': 'Cone',
    'container': 'Container',
    'contract': 'Contract',
    'coptic': 'Do not use',
    'cornflowers': 'Cornflowers',
    'cosmetic': 'Cosmetic',
    'cow plaque': 'Plaque',
    'cowroid': 'Cowroid',
    'crocodile': 'Crocodile',
    'cup': 'Cup',
    'currency': 'Currency',
    'cylinder': 'Cylinder',
    'cylinder seal': 'Cylinder seal',
    'cylinder vase': 'Vase',
    'cylindrical': 'Do not use',
    'daisy': 'Daisy',
    'dead bride': 'Do not use',
    'decorated ware': 'Decorated ware',
    'decorative belt': 'Belt',
    'demotic': 'Demotic',
    'detailed back': 'Do not use',
    'dice': 'Dice',
    'diocletian': 'Do not use',
    'dish': 'Dish',
    'disk': 'Disk',
    'djed pillar': 'Djed pillar',
    'djeserkare': 'Do not use',
    'document': 'Document',
    'double': 'Do not use',
    'drawing': 'Drawing',
    'duamutef': 'Do not use',
    'duck': 'Duck',
    'earring': 'Earring',
    'earrings': 'Earring',
    'edge shard': 'Shard',
    'execration': 'Execration',
    'eye': 'Eye',
    'eye plaque': 'Eye plaque',
    'face': 'Do not use',
    'facsimile': 'Facsimile',
    'falcon': 'Falcon',
    'falcon amulet': 'Amulet',
    'fashion model': 'Model',
    'female': 'Do not use',
    'figure': 'Figure',
    'figured': 'Do not use',
    'figurine': 'Figurine',
    'figurines': 'Figurine',
    'finger rings': 'Rings',
    'finger stall': 'Finger stall',
    'fire/heat': 'Do not use',
    'fish': 'Fish',
    'floral': 'Do not use',
    'folios (leaves)': 'Folio',
    'food': 'Food/drink',
    'food/drink': 'Food/drink',
    'foreigner': 'Do not use',
    'foreigners': 'Do not use',
    'forgery': 'Forgery',
    'foundation deposit': 'Foundation deposit',
    'foundation deposit material': 'Foundation deposit',
    'foundation deposit plaque': 'Foundation deposit',
    'fragment': 'Do not use',
    'fragments': 'Do not use',
    'frog': 'Frog',
    'funeral sign': 'Do not use',
    'funerary': 'Funerary object',
    'funerary cone': 'Funerary cone',
    'funerary figure': 'Figure',
    'funerary object': 'Funerary object',
    'furniture': 'Furniture',
    'game piece': 'Game piece',
    'games': 'Game',
    'glass': 'Glass',
    'glass fragment': 'Glass',
    'glasswares': 'Glass',
    'god': 'Do not use',
    "god's wife": 'Do not use',
    'goddess': 'Do not use',
    'gold': 'Do not use',
    'gold and silver': 'Do not use',
    'granulation': 'Do not use',
    'grapes': 'Grape',
    'greek': 'Do not use',
    'group 2': 'Do not use',
    'group 3': 'Do not use',
    'group model': 'Model',
    'hadra': 'Hadra',
    'hadrian': 'Do not use',
    'hair pin': 'Hair pin',
    'hand': 'Hand',
    'handwriting': 'Do not use',
    'hapiankhtifi': 'Do not use',
    'hapy': 'Do not use',
    'harpokrates': 'Do not use',
    'hathor': 'Do not use',
    'hathor emblem': 'Hathor emblem',
    'hathor head': 'Hathor head',
    'hatshepsut': 'Do not use',
    'head': 'Head',
    'headrest': 'Headrest',
    'heart': 'Heart',
    'heart scarab': 'Scarab',
    'hieratic': 'Hieratic',
    'hieroglyph': 'Hieroglyph',
    'hieroglyphs': 'Hieroglyph',
    'hippopotamus': 'Hippopotamus',
    'hippopotamus head amulet': 'Amulet',
    'horse': 'Horse',
    'horus': 'Do not use',
    'horus chicken': 'Horuscippus',
    'house mistress': 'Do not use',
    'human': 'Do not use',
    'hydria': 'Hydria',
    'ibex': 'Ibex',
    'illuminated manuscripts': 'Manuscript',
    'imhotep': 'Do not use',
    'imsety': 'Do not use',
    'index': 'Do not use',
    'inlay': 'Inlay',
    'inner box': 'Box',
    'inscribed': 'Do not use',
    'inscription': 'Do not use',
    'interior surface': 'Do not use',
    'ipuy (tt 217)': 'Do not use',
    'isis': 'Do not use',
    'ivory & bone': 'Do not use',
    'jackal': 'Jackal',
    'jar': 'Jar',
    'jar fragment': 'Jar',
    'jar label': 'Jar label',
    'jewelry': 'Jewelry',
    'jug': 'Jug',
    'khonsu': 'Do not use',
    'king': 'King',
    'knife': 'Knife',
    'kohl jar': 'Kohl jar',
    'kohl stick': 'Kohl stick',
    'kohl tube': 'Kohl tube',
    'lamp': 'Lamp',
    'letter': 'Letter',
    'lid': 'Lid',
    'linen': 'Linen',
    'linen fragment': 'Linen',
    'linen mark': 'Linen',
    'linen sheet': 'Linen',
    'linen sheet or shawl': 'Linen',
    'lion': 'Lion',
    'lord of the two lands': 'Do not use',
    'lotiform': 'Do not use',
    'lotus': 'Do not use',
    'lotus-shaped': 'Do not use',
    'lug handles': 'Do not use',
    'maat': 'Do not use',
    'maatkare': 'Do not use',
    'magic': 'Do not use',
    'magic wand': 'Magic wand',
    'magical': 'Do not use',
    'mallet': 'Mallet',
    'mammal': 'Mammal',
    'man': 'Do not use',
    'manuscripts & rare books': 'Manuscript',
    'mark': 'Do not use',
    'mask': 'Mask',
    'maximianus': 'Do not use',
    'menat fragment': 'Menat',
    'menkheperre': 'Do not use',
    'meroïtic': 'Do not use',
    'metal': 'Do not use',
    'min': 'Do not use',
    'miniature': 'Do not use',
    'miniature bottle': 'Miniature bottle',
    'miniature bowl': 'Miniature bowl',
    'mirror': 'Mirror',
    'miscellaneous': 'Do not use',
    'model': 'Model',
    'model dish': 'Model dish',
    'model vase': 'Model vase',
    'models (representations)': 'Model',
    'mold': 'Mold',
    'monkey': 'Monkey',
    'mummy': 'Mummy',
    'mummy chest': 'Mummy chest',
    'mummy cloth fragment': 'Mummy Cloth',
    'mummy holder': 'Mummy holder',
    'music': 'Music',
    'musical instrument': 'Music',
    'nail': 'Nail',
    'nany': 'Do not use',
    'nb': 'Do not use',
    'nebmaatre': 'Do not use',
    'necklace': 'Necklace',
    'necklaces': 'Necklace',
    'nefer': 'Do not use',
    'neferkhawet': 'Do not use',
    'neferu': 'Do not use',
    'neferure': 'Do not use',
    'neith': 'Do not use',
    'nephthys': 'Do not use',
    'nfr': 'Do not use',
    'notched back': 'Do not use',
    'object': 'Do not use',
    'offering': 'Offering',
    'offering table': 'Offering table',
    'offerings': 'Offering',
    'official': 'Do not use',
    'oil lamp': 'Oil lamp',
    'ointment': 'Ointment',
    'ointment jar': 'Ointment jar',
    'openwork': 'Do not use',
    'ornament': 'Do not use',
    'osiris': 'Do not use',
    'ostracon': 'Ostracon',
    'oval impression': 'Impression',
    'overseer': 'Do not use',
    'paint': 'Do not use',
    'painted': 'Do not use',
    'painting': 'Painting',
    'palace of ramesses ii': 'Palace of Ramesses II',
    'palette': 'Palette',
    'papyrus': 'Papyrus',
    'pataikos': 'Pataikos',
    'pectoral': 'Pectoral',
    'pen drawing': 'Drawing',
    'penannular': 'Do not use',
    'pendant': 'Pendant',
    'pendants': 'Pendant',
    'perneb': 'Do not use',
    'persea fruit': 'Food/drink',
    'person': 'Do not use',
    'piriform': 'Do not use',
    'pitcher': 'Pitcher',
    'plaque': 'Plaque',
    'plaques': 'Plaque',
    'plaques (flat objects)': 'Plaque',
    'plate': 'Plate',
    'pleating': 'Do not use',
    'pot': 'Pot',
    'precious stones & gems': 'Do not use',
    'priest': 'Priest',
    'prince amenemhat': 'Do not use',
    'private': 'Do not use',
    'probus': 'Do not use',
    'ptah': 'Do not use',
    'ptolemy ii': 'Do not use',
    'puyemre (tt 39)': 'Do not use',
    'qenamun (tt 93)': 'Do not use',
    'queen tiye': 'Do not use',
    'ramesses ii': 'Do not use',
    'ramesses iii': 'Do not use',
    'ramesses iv': 'Do not use',
    're': 'Do not use',
    'recipe': 'Do not use',
    'recreation': 'Recreation',
    'rectangular': 'Do not use',
    'red crown': 'Red crown',
    'red polished ware': 'Do not use',
    'rekhmire (tt 100)': 'Do not use',
    'relief': 'Relief',
    'relief fragment': 'Relief',
    'reliefs': 'Relief',
    'remains': 'Do not use',
    'rennefer': 'Do not use',
    'reptile': 'Reptile',
    'ribs': 'Ribs',
    'ring': 'Ring',
    'ring fragment': 'Ring',
    'rosette': 'Rosette',
    'royal': 'Do not use',
    'ruiu': 'Do not use',
    'sahidic': 'Do not use',
    'sakhmet': 'Do not use',
    'scarab': 'Scarab',
    'scaraboid': 'Scaraboid',
    'scarabs': 'Scarab',
    'scribe': 'Scribe',
    "sculptor's model/votive": "Sculptor's model",
    'sculpture': 'Sculpture',
    'sculpture (visual works)': 'Sculpture',
    'sculptures': 'Sculpture',
    'seal': 'Seal',
    'seal amulet': 'Amulet',
    'seal ring': 'Seal ring',
    'sealing': 'Sealing',
    'senebtisi': 'Do not use',
    'senenmut': 'Do not use',
    'senwosret i': 'Do not use',
    'sermon': 'Do not use',
    'seti i': 'Do not use',
    'seti ii': 'Do not use',
    'shabaqo': 'Do not use',
    'shabti': 'Shabti',
    'shabti box': 'Shabti box',
    'shard': 'Shard',
    'sheet': 'Sheet',
    'shell': 'Shell',
    'shroud': 'Shroud',
    'shu': 'Do not use',
    'shuttle': 'Shuttle',
    'signet': 'Signet',
    'silver & jewelry': 'Jewelry',
    'simple back': 'Do not use',
    'siptah': 'Do not use',
    'sistrum': 'Sistrum',
    'sithathoryunet': 'Do not use',
    'situla': 'Situla',
    'small statue': 'Statue',
    'spacer': 'Spacer',
    'sphinx': 'Sphinx',
    'spirals': 'Do not use',
    'staff': 'Staff',
    'stamp': 'Stamp',
    'stamp seal': 'Sealing',
    'statue': 'Statue',
    'statues': 'Statue',
    'statuette': 'Statuette',
    'statuettes': 'Statuette',
    'statuettes (statues)': 'Statuette',
    'stela': 'Stela',
    'stelae': 'Stela',
    'steward': 'Do not use',
    'stick': 'Stick',
    'string': 'Do not use',
    'sun bark': 'Sun bark',
    'sun disk': 'Sun disk',
    'sunk relief': 'Do not use',
    'tablet': 'Tablet',
    'talatat': 'Talatat',
    'taweret': 'Do not use',
    'tawosret': 'Do not use',
    'temple utensils': 'Temple utensils',
    'terracottas': 'Terracotta',
    'tetiky': 'Do not use',
    'tetradrachm': 'Tetradrachme',
    'tetradrachme': 'Tetradrachme',
    'textile': 'Textile',
    'textiles': 'Textile',
    'thoth': 'Do not use',
    'thutmose i': 'Do not use',
    'thutmose iii': 'Do not use',
    'thutmose iv': 'Do not use',
    'tile': 'Tile',
    'tile fragment': 'Tile',
    'tiles': 'Tiles',
    'tissue': 'Tissue',
    'tiye': 'Do not use',
    'toe stall': 'Toe stall',
    'tomb of khety': 'Do not use',
    'tomb of meketre': 'Do not use',
    'tomb of nespekashuty': 'Do not use',
    'tool': 'Tool',
    'top surface': 'Do not use',
    'toys': 'Toy',
    'trajan': 'Do not use',
    'tufted': 'Do not use',
    'tweezers': 'Tweezers',
    'umbel': 'Umbel',
    'uninscribed': 'Do not use',
    'upholstery': 'Upholstery',
    'uraei': 'Uraeus',
    'uraeus': 'Uraeus',
    'userhat (tt 51)': 'Do not use',
    'ushabti': 'Shabti',
    'ushebti': 'Shabti',
    'vase': 'Vase',
    'vase fragment': 'Vase',
    'vases': 'Vase',
    'vespasian': 'Do not use',
    'vessel': 'Vessel',
    'vessel fragment': 'Vessel',
    'vessels': 'Vessel',
    'vignettes': 'Vignette',
    'votive': 'Do not use',
    'votive image': 'Votive image',
    'vulture': 'Vulture',
    'wah': 'Do not use',
    'wall casing': 'Do not use',
    'walls': 'Do not use',
    'weaving weight': 'Weight',
    'wedjat eye': 'Wedjat eye',
    'weight': 'Weight',
    'weights/measures': 'Weight',
    'white cross-lined ware': 'Ware',
    'winged scarab': 'Scarab',
    'woman': 'Do not use',
    '|': 'Do not use',
    '||': 'Do not use'
}

OBJECT_TYPE_SYNONYMS_NL = {
    '"tell basta treasure"': 'Do not use',
    '(niet toegekend)': 'Do not use',
    'aap': 'Aap',
    'accessoires': 'Accessoire',
    'achnaton': 'Do not use',
    'aes-24': 'Do not use',
    'aes-33': 'Do not use',
    'afdichting': 'Afdichting',
    'afgietsel': 'Afgietsel',
    'ahmose': 'Do not use',
    'ahmose-nefertari': 'Do not use',
    'ajour (werk)': 'Do not use',
    'alabastron': 'Alabastron',
    'amasis': 'Do not use',
    'ambtenaar': 'Do not use',
    'amdoeat': 'Amdoeat',
    'amenemhat': 'Do not use',
    'amenemhat i': 'Do not use',
    'amenemhat iii': 'Do not use',
    'amenhotep': 'Do not use',
    'amenhotep i': 'Do not use',
    'amenhotep ii': 'Do not use',
    'amenhotep iii': 'Do not use',
    'amfoor': 'Amfoor',
    'amon': 'Do not use',
    'amulet': 'Amulet',
    'amulet -hanganten': 'Hanger',
    'amulet hanger': 'Hanger',
    'amulet-afhankelijk': 'Amulet',
    'amuletten': 'Amulet',
    'amun': 'Do not use',
    'amun-re': 'Do not use',
    'ankh': 'Do not use',
    'anubis': 'Do not use',
    'apen amulet': 'Amulet',
    'apries': 'Do not use',
    'architecturaal element': 'Architecturaal element',
    'arm': 'Armband',
    'armband': 'Armband',
    'armband (armband)': 'Armband',
    'armen en wapenrusting': 'Wapen',
    'aten cartouche': 'Do not use',
    'aten cartouches': 'Do not use',
    'bal': 'Bal',
    'bandage': 'Bandage',
    'bastet': 'Do not use',
    'bat': 'Do not use',
    'baviaan': 'Baviaan',
    'bead': 'Kraal',
    'bead plaque': 'Plaque',
    'bedacht': 'Do not use',
    'beeld': 'Beeld',
    'beelden': 'Beeld',
    'beeldhouwersmodel': 'Beeldhouwersmodel',
    'beeldhouwkunst (visuele werken)': 'beeldhouwwerk',
    'beeldhouwwerk': 'beeldhouwwerk',
    'beeldhouwwerken': 'beeldhouwwerk',
    'beeldje': 'Beeldje',
    'beeldjes': 'Beeldje',
    'beeldjes (standbeelden)': 'Beeldje',
    'begrafenis': 'Do not use',
    'beitel': 'Beitel',
    'beker': 'Beker',
    'bekleedsel': 'Bekleedsel',
    'bes': 'Do not use',
    'bijl': 'Bijl',
    'binnenkist': 'Kist',
    'blad': 'Blad',
    'bloemen': 'Bloem',
    'breed halsband': 'Ketting',
    'brief': 'Brief',
    'brons': 'Do not use',
    'buitenlander': 'Do not use',
    "calf's head": 'Koehoofd',
    'canope': 'Canope',
    'canopenkist': 'Canopenkist',
    'canopenkoffer': 'Canopenkist',
    'canopenvaas': 'Canope',
    'canopenvaas-deksel': 'Canope',
    'cartonnage': 'Cartonnage',
    'cartouche': 'Cartouche',
    'cat': 'Kat',
    'cilinder': 'Cilinder',
    'cilinder zegel': 'Cilinder zegel',
    'cilindervaas': 'Vaas',
    'cilindrisch': 'Do not use',
    'circulair': 'Do not use',
    'cirkelvormige indruk': 'Afdruk',
    'clavus': 'Do not use',
    'coffin': 'Mummiekist',
    'coffin inlegwerk': 'Inlegwerk',
    'cone': 'Kegel',
    'contract': 'Contract',
    'cowroid': 'Cowroïde',
    'cowroïde': 'Cowroïde',
    'deksel': 'Deksel',
    'demotisch': 'Demotisch',
    'dier': 'Dier',
    'diocletianus': 'Do not use',
    'djed pijler': 'Djed-pijler',
    'djeserkare': 'Do not use',
    'dobbelsteen': 'Dobbelsteen',
    'document': 'Document',
    'dodenboek': 'Dodenboek',
    'dodenbruid': 'Do not use',
    'druiven': 'Druif',
    'duamutef': 'Do not use',
    'dubbel': 'Do not use',
    'dubbele rol': 'Do not use',
    'edelstenen en edelstenen': 'Do not use',
    'eend': 'Eend',
    'eenvoudige achterkant': 'Do not use',
    'enkelring': 'Enkelband',
    'execration': 'Execratie',
    'facsimile': 'Facsimile',
    'falcon': 'Valk',
    'figuur': 'Figuur',
    'figuurtje': 'Figuurtje',
    'fire / heat': 'Do not use',
    'fles': 'Fles',
    "folio's (bladeren)": 'Folio',
    'fragment': 'Do not use',
    'fragmenten': 'Do not use',
    'funderingsdepot': 'Funderingsdepot',
    'funderingsdepot materiaal': 'Funderingsdepot',
    'funderingsdepot plaque': 'Funderingsdepot',
    'funerair figuur': 'Figuur',
    'funerary object': 'Funerair object',
    'gedecoreerde waren': 'Aardewerk',
    'gedenkplaat': 'Gedenkplaat',
    'gedetailleerd terug': 'Do not use',
    'gereedschap': 'Gereedschap',
    'geschilderd': 'Do not use',
    'getuft': 'Do not use',
    'geurtje': 'Do not use',
    'gevleugelde scarabee': 'Scarabee',
    'gewicht': 'Gewicht',
    'gewichten / maatregelen': 'Gewicht',
    'gezicht': 'Gezicht',
    'gier': 'Gier',
    'gietvorm': 'Gietvorm',
    'glas': 'Glas',
    'glasswares': 'Glas',
    'god': 'Do not use',
    "god's wife": 'Do not use',
    'godin': 'Do not use',
    'gods vrouw': 'Do not use',
    'gordel': 'Gordel',
    'goud': 'Do not use',
    'goud en zilver': 'Do not use',
    'graf van khety': 'Do not use',
    'graf van meketre': 'Do not use',
    'graf van nespekashuty': 'Do not use',
    'grafbord': 'Grafbord',
    'grafkegel': 'Grafkegel',
    'granulatie': 'Do not use',
    'grieks': 'Do not use',
    'groep 2': 'Do not use',
    'groepsmodel': 'Model',
    'grote dikbuikige kruik': 'Kruik',
    'grote dikbuikige kruik fragment': 'Kruik',
    'haar pin': 'Haarpin',
    'hadra': 'Hadra',
    'hadrianus': 'Do not use',
    'halsketting': 'Halsketting',
    'halssnoer': 'Halssnoer',
    'hamer': 'Hamer',
    'hand': 'Hand',
    'handschrift': 'Do not use',
    'handvatten': 'Do not use',
    'hanger': 'Hanger',
    'hangers': 'Hanger',
    'hapiankhtifi': 'Do not use',
    'hapy': 'Do not use',
    'harpokrates': 'Do not use',
    'hart': 'Hart',
    'hart scarabee': 'Scarabee',
    'hathor': 'Do not use',
    'hathor hoofd': 'Do not use',
    'hathor-embleem': 'Do not use',
    'hatshepsut': 'Do not use',
    'hendel': 'Do not use',
    'hieratic': 'Hiëratisch',
    'hippopotamus hoofdamulet': 'Amulet',
    'hiëratisch': 'Hiëratisch',
    'hiëroglief': 'Hiëroglief',
    'hiërogliefen': 'Hiëroglief',
    'hond': 'Hond',
    'hoofd': 'Hoofd',
    'hoofdsteun': 'Hoofdsteun',
    'horus': 'Do not use',
    'horuscippus': 'Horuscippus',
    'houder': 'Houder',
    'huismeesteres': 'Do not use',
    'huisraad en meubilair': 'Meubilair',
    'hydria': 'Hydria',
    'ibex': 'Ibex',
    'imhotep': 'Do not use',
    'imsety': 'Do not use',
    'index': 'Do not use',
    'ingekerfd': 'Do not use',
    'ingeschreven': 'Do not use',
    'inlegsel': 'Inlegwerk',
    'inlegwerk': 'Inlegwerk',
    'ipuy (tt 217)': 'Do not use',
    'isis': 'Do not use',
    'ivoor & gebeente': 'Do not use',
    'jakhals': 'Jakhals',
    'juwelen': 'Juwelen',
    'kam': 'Kam',
    'kan': 'Kan',
    'kat': 'Kat',
    'kegel': 'Kegel',
    'kelk': 'Kelk',
    'keramiek': 'Keramiek',
    'kettingen': 'Ketting',
    'khonsu': 'Do not use',
    'kikker': 'Kikker',
    'kind': 'Kind',
    'kist': 'Kist',
    'klein beeld': 'Statue',
    'kleisteen': 'Do not use',
    'klepel': 'Klepel',
    'knopzegel': 'Knopzegel',
    'koeienplak': 'Plaque',
    'kohlbuis': 'Kohlbuis',
    'kom': 'Kom',
    'kom fragment': 'Kom',
    'koning': 'Do not use',
    'kool grote dikbuikige kruik': 'Kruik',
    'koolstok': 'Do not use',
    'kooltube': 'Kooltube',
    'koptisch': 'Do not use',
    'korenbloemen': 'Korenbloem',
    'korf': 'Korf',
    'kraal': 'Kraal',
    'kralen': 'Kraal',
    'krokodil': 'Krokodil',
    'kruik': 'Kruik',
    'lamp': 'Lamp',
    'leeuw': 'Leeuw',
    'lichaamsdeel': 'Lichaamsdeel',
    'linnen': 'Linnen',
    'linnen doek': 'Linnen',
    'linnen fragment': 'Linnen',
    'linnen laken of sjaal': 'Linnen',
    'linnen lakens': 'Linnen',
    'linnen mark': 'Linnen',
    'linnen merk': 'Linnen',
    'lotiform': 'Do not use',
    'lotus': 'Do not use',
    'lotus-vormig': 'Do not use',
    'maat': 'Do not use',
    'maatkare': 'Do not use',
    'madeliefje': 'Madeliefje',
    'magie': 'Do not use',
    'magisch': 'Do not use',
    'mama': 'Do not use',
    'man': 'Do not use',
    'manuscripten en zeldzame boeken': 'Manuscript',
    'mark': 'Do not use',
    'masker': 'Masker',
    'maximianus': 'Do not use',
    'medeplichtig': 'Accessoire',
    'menat fragment': 'Menat',
    'menkheperre': 'Do not use',
    'mens': 'Do not use',
    'meroïtisch': 'Do not use',
    'mes': 'Mes',
    'metaal': 'Do not use',
    'min': 'Do not use',
    'miniatuur': 'Miniatuur',
    'miniatuurfles': 'Miniatuurfles',
    'miniatuurkom': 'Miniatuurkom',
    'model': 'Model',
    'model vaas': 'Modelvaas',
    'model-': 'Do not use',
    'modellen (afbeeldingen)': 'Model',
    'modellen (representaties)': 'Model',
    'mummie': 'Mummie',
    'mummie doek fragment': 'Miummiedoek',
    'mummie-etiket': 'Do not use',
    'mummiedoek': 'Mummiedoek',
    'mummiehouder': 'Mummiehouder',
    'mummiekist': 'Mummiekist',
    'mummiekleed': 'Mummiekleed',
    'mummy cloth fragment': 'Mummieweefsel',
    'munt': 'Munt',
    'munten': 'Munt',
    'muurbehuizing': 'Do not use',
    'muziek': 'Muziek',
    'muziekinstrument': 'Muziek',
    'nany': 'Do not use',
    'nb': 'Do not use',
    'nebmaatre': 'Do not use',
    'nefer': 'Do not use',
    'neferkhawet': 'Do not use',
    'neferu': 'Do not use',
    'neferure': 'Do not use',
    'neith': 'Do not use',
    'nephthys': 'Do not use',
    'nfr': 'Do not use',
    'niet beschreven': 'Do not use',
    'nijlpaard': 'Nijlpaard',
    'oesjabikist': 'Sjabikist',
    'oesjabti': 'Oesjabti',
    'oesjebti': 'Oesjabti',
    'offertafel': 'Offertafel',
    'olielamp': 'Olielamp',
    'oog': 'Oog',
    'oogplak': 'Do not use',
    'oorring': 'Oorring',
    'opzichter': 'Do not use',
    'ornament': 'Ornament',
    'osiris': 'Do not use',
    'ostracon': 'Ostracon',
    'ovale indruk': 'Afdruk',
    'paard': 'Paard',
    'paleis van ramses ii': 'Paleis van Ramses II',
    'palet': 'Palet',
    'palm': 'Palm',
    'papyrus': 'Papyrus',
    'pataikos': 'Pataikos',
    'pectoraal': 'Pectoraal',
    'penannular': 'Do not use',
    'pentekening': 'Tekening',
    'perneb': 'Do not use',
    'persea fruit': 'Voedsel/drinken',
    'persoon': 'Do not use',
    'pijl': 'Pijl',
    'pijlpunt': 'Pijlpunt',
    'pion': 'Pion',
    'piriform': 'Do not use',
    'plaque': 'Plaque',
    'plaques': 'Plaque',
    'plaques (platte objecten)': 'Plaque',
    'plooien': 'Do not use',
    'pot': 'Pot',
    'preek': 'Do not use',
    'priester': 'Do not use',
    'privé': 'Do not use',
    'probus': 'Do not use',
    'ptah': 'Do not use',
    'ptolemaeus ii': 'Do not use',
    'puyemre (tt 39)': 'Do not use',
    'qenamun (tt 93)': 'Do not use',
    'queen tiye': 'Do not use',
    'ramesses iv': 'Do not use',
    'ramses ii': 'Do not use',
    'ramses iii': 'Do not use',
    'randscherf': 'Scherf',
    're': 'Do not use',
    'recept': 'Recept',
    'rechthoekig': 'Do not use',
    'recreatie': 'Recreatie',
    'rectangular': 'Do not use',
    'rekhmire (tt 100)': 'Do not use',
    'reliëf': 'Reliëf',
    'reliëf-fragment': 'Reliëf',
    'reliëfs': 'Reliëf',
    'rennefer': 'Do not use',
    'rentmeester': 'Do not use',
    'reptiel': 'Reptiel',
    'resten': 'Do not use',
    'ribben': 'Rib',
    'ring': 'Ring',
    'ringfragment': 'Ring',
    'rond': 'Do not use',
    'ronde indruk': 'Afdruk',
    'rood gepolijst aardewerk': 'Aardewerk',
    'rozet': 'Rozet',
    'ruiu': 'Do not use',
    'sahidisch': 'Do not use',
    'sakhmet': 'Do not use',
    'scarabee': 'Scarabee',
    'scarabee-achtig voorwerp': 'Scaraboïde',
    'scaraboïde': 'Scaraboïde',
    'scarabs': 'Scarabee',
    'schaal': 'Schaal',
    'schaalmodel': 'Schaalmodel',
    'schelp': 'Schelp',
    'schepen': 'Schip',
    'scherf': 'Scherf',
    'scherm': 'Scherm',
    'schietspoel': 'Schietspoel',
    'schijf': 'Schijf',
    'schilderij': 'Do not use',
    'schimmel': 'Schimmel',
    'schoonheidsmiddel': 'Schoonheidsmiddel',
    'schrijver': 'Schrijver',
    'senebtisi': 'Do not use',
    'senenmut': 'Do not use',
    'senwosret i': 'Do not use',
    'seti i': 'Do not use',
    'seti ii': 'Do not use',
    'sfinx': 'Sfinx',
    'shabaqo': 'Do not use',
    'shu': 'Do not use',
    'sierband': 'Sierband',
    'siptah': 'Do not use',
    'sistrum': 'Sistrum',
    'sithathoryunet': 'Do not use',
    'situla': 'Situla',
    'spacer': 'Do not use',
    'speelgoed': 'Speelgoed',
    'spellen': 'Speelgoed',
    'spiegel': 'Spiegel',
    'spijker': 'Spijker',
    'spiralen': 'Spiraal',
    'spoel': 'Spoel',
    'staf': 'Staf',
    'stamp zegel': 'Afdruk',
    'standbeelden': 'Standbeeld',
    'stelae': 'Stèle',
    'stier': 'Stier',
    'stok': 'Stok',
    'stèle': 'Stèle',
    'tablet': 'Tablet',
    'talatat': 'Talatat',
    'taweret': 'Do not use',
    'tawosret': 'Do not use',
    'tegel': 'Tegel',
    'tegels': 'Tegel',
    'tekening': 'Tekening',
    'tempelgerei': 'Tempelgerei',
    'terracotta': 'Terracotta',
    'tetiky': 'Do not use',
    'tetradrachme': 'Tetradrachme',
    'textiel': 'Textiel',
    'textiles': 'Textiel',
    'thoetmosis iii': 'Do not use',
    'thoth': 'Do not use',
    'thutmose i': 'Do not use',
    'thutmose iii': 'Do not use',
    'thutmose iv': 'Do not use',
    'tiye': 'Do not use',
    'toe stall': 'Do not use',
    'tomb of nespekashuty': 'Do not use',
    'touw': 'Touw',
    'toverstaf': 'Toverstaf',
    'trajanus': 'Do not use',
    'uraei': 'Uraeus',
    'uraeus': 'Uraeus',
    'userhat (tt 51)': 'Do not use',
    'ushabti': 'Shabti',
    'vaartuig': 'Vaartuig',
    'vaas': 'Vaas',
    'vaas-fragment': 'Vaas',
    'vaasetiket': 'Do not use',
    'valk': 'Valk',
    'valk-amulet': 'Amulet',
    'valuta': 'Munt',
    'varia': 'Do not use',
    'vatfragment': 'Vat',
    'vazen': 'Vaas',
    'vee': 'Vee',
    'verf': 'Verf',
    'verlichte manuscripten': 'Manuscript',
    'vervalsing': 'Vervalsing',
    'verzonken reliëf': 'Reliëf',
    'vespasianus': 'Do not use',
    'vignetten': 'Vignet',
    'vinger ringen': 'Ring',
    'vingerkraam': 'Do not use',
    'vis': 'Vis',
    'vlieg': 'Vlieg',
    'voedsel': 'Voedsel/drinken',
    'voedsel / drinken': 'Voedsel/drinken',
    'vogel': 'Vogel',
    'voorwerp': 'Do not use',
    'votiefbeeld': 'Votiefbeeld',
    'votive': 'Do not use',
    'vrouw': 'Do not use',
    'wah': 'Do not use',
    'wanden': 'Do not use',
    'wedjat-oog': 'Wedjat-oog',
    'weefgewicht': 'Gewicht',
    'weefsel': 'Weefsel',
    'zalf': 'Zalf',
    'zalf grote dikbuikige kruik': 'Kruik',
    'zegel': 'Zegel',
    'zegel-amulet': 'Amulet',
    'zegelring': 'Zegelring',
    'zilver en sieraden': 'Do not use',
    'zonneschijf': 'Zonneschijf',
    'zoogdier': 'Zoogdier',
    '|': 'Do not use',
    '||': 'Do not use'
}
