# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.TextField(unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='collection_images')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Title of the object', max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of the object', null=True, verbose_name='Description')),
                ('title_orig', models.CharField(blank=True, help_text='Title of the object', max_length=255, null=True, verbose_name='Original title')),
                ('description_orig', models.TextField(blank=True, help_text='Description of the object', null=True, verbose_name='Original description')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importer_uid', models.CharField(max_length=255, verbose_name='Importer UID')),
                ('inventory_number', models.CharField(blank=True, help_text='Inventory number in the museum collection', max_length=255, null=True, verbose_name='Inventory number')),
                ('api_url', models.CharField(help_text='Link to original data in API', max_length=255, verbose_name='API item URL')),
                ('web_url', models.CharField(blank=True, help_text='Link to external data URL', max_length=255, null=True, verbose_name='External item URL')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Title of the object', max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of the object', null=True, verbose_name='Description')),
                ('department', models.CharField(blank=True, help_text='Department of the museum', max_length=255, null=True, verbose_name='Department')),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions of the object', max_length=255, null=True, verbose_name='Dimensions')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=255, null=True, verbose_name='State/province')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('object_type', models.CharField(blank=True, help_text='Type of object', max_length=255, null=True, verbose_name='Object type')),
                ('material', models.CharField(blank=True, help_text='Material(s) of which the object is made', max_length=255, null=True, verbose_name='Material')),
                ('acquired', models.CharField(blank=True, help_text='How the museum acquired the object', max_length=255, null=True, verbose_name='Acquired')),
                ('site_found', models.CharField(blank=True, help_text='Complete record of site where the object was found', max_length=255, null=True, verbose_name='Site found')),
                ('title_orig', models.CharField(blank=True, help_text='Title of the object', max_length=255, null=True, verbose_name='Original title')),
                ('description_orig', models.TextField(blank=True, help_text='Description of the object', null=True, verbose_name='Original description')),
                ('department_orig', models.CharField(blank=True, help_text='Department of the museum', max_length=255, null=True, verbose_name='Original department')),
                ('dimensions_orig', models.CharField(blank=True, help_text='Dimensions of the object', max_length=255, null=True, verbose_name='Original dimensions')),
                ('city_orig', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original city')),
                ('state_province_orig', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original state/province')),
                ('country_orig', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original country')),
                ('object_type_orig', models.CharField(blank=True, help_text='Type of object', max_length=255, null=True, verbose_name='Original object type')),
                ('material_orig', models.CharField(blank=True, help_text='Material(s) of which the object is made', max_length=255, null=True, verbose_name='Original material')),
                ('acquired_orig', models.CharField(blank=True, help_text='How the museum acquired the object', max_length=255, null=True, verbose_name='Original acquired')),
                ('site_found_orig', models.CharField(blank=True, help_text='Complete record of site where the object was found', max_length=255, null=True, verbose_name='Original site found')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muses_collection.Item'),
        ),
    ]
