# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='item',
            name='state_province_orig',
        ),
        migrations.AddField(
            model_name='item',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period end'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_end_orig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original period end'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_orig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Period'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period start'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_start_orig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original period start'),
        ),
        migrations.AddField(
            model_name='item',
            name='record_number',
            field=models.CharField(blank=True, help_text='Record number', max_length=255, null=True, verbose_name='Record number'),
        ),
        migrations.AddField(
            model_name='item',
            name='references',
            field=models.TextField(blank=True, help_text='References to this object in the professional literature', null=True, verbose_name='References'),
        ),
        migrations.AddField(
            model_name='item',
            name='references_orig',
            field=models.TextField(blank=True, help_text='References to this object in the professional literature', null=True, verbose_name='Original references'),
        ),
    ]
