# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0002_auto_20180206_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='muses_collection.Image', verbose_name='Images'),
        ),
    ]
