# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0003_auto_20180207_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='acquired',
            field=models.TextField(blank=True, help_text='How the museum acquired the object', null=True, verbose_name='Acquired'),
        ),
        migrations.AlterField(
            model_name='item',
            name='acquired_orig',
            field=models.TextField(blank=True, help_text='How the museum acquired the object', null=True, verbose_name='Original acquired'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.TextField(blank=True, help_text='Dimensions of the object', null=True, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions_orig',
            field=models.TextField(blank=True, help_text='Dimensions of the object', null=True, verbose_name='Original dimensions'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.TextField(blank=True, help_text='Material(s) of which the object is made', null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material_orig',
            field=models.TextField(blank=True, help_text='Material(s) of which the object is made', null=True, verbose_name='Original material'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period',
            field=models.TextField(blank=True, null=True, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Original Period'),
        ),
    ]
