# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0005_auto_20180207_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='image',
            name='api_url',
            field=models.TextField(unique=True, verbose_name='Image API URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Date imported'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='collection_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Date updated'),
        ),
    ]
