# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0006_auto_20180207_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='language_code_orig',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Language code of the original'),
        ),
    ]
