# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0007_item_language_code_orig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='acquired',
        ),
        migrations.RemoveField(
            model_name='item',
            name='department',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.RemoveField(
            model_name='item',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='period',
        ),
        migrations.RemoveField(
            model_name='item',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='item',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='item',
            name='references',
        ),
        migrations.RemoveField(
            model_name='item',
            name='site_found',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='acquired_en',
            field=models.TextField(blank=True, help_text='How the museum acquired the object', null=True, verbose_name='Acquired (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='department_en',
            field=models.CharField(blank=True, help_text='Department of the museum', max_length=255, null=True, verbose_name='Department (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description of the object', null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='dimensions_en',
            field=models.TextField(blank=True, help_text='Dimensions of the object', null=True, verbose_name='Dimensions (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='material_en',
            field=models.TextField(blank=True, help_text='Material(s) of which the object is made', null=True, verbose_name='Material (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='object_type_en',
            field=models.CharField(blank=True, help_text='Type of object', max_length=255, null=True, verbose_name='Object type (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_en',
            field=models.TextField(blank=True, null=True, verbose_name='Period (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_end_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period end (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_start_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period start (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='references_en',
            field=models.TextField(blank=True, help_text='References to this object in the professional literature', null=True, verbose_name='References (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='site_found_en',
            field=models.CharField(blank=True, help_text='Complete record of site where the object was found', max_length=255, null=True, verbose_name='Site found (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title of the object', max_length=255, null=True, verbose_name='Title (EN)'),
        ),
    ]
