# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0008_auto_20180430_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='acquired_nl',
            field=models.TextField(blank=True, help_text='How the museum acquired the object', null=True, verbose_name='Acquired (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='department_nl',
            field=models.CharField(blank=True, help_text='Department of the museum', max_length=255, null=True, verbose_name='Department (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_nl',
            field=models.TextField(blank=True, help_text='Description of the object', null=True, verbose_name='Description (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='dimensions_nl',
            field=models.TextField(blank=True, help_text='Dimensions of the object', null=True, verbose_name='Dimensions (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='material_nl',
            field=models.TextField(blank=True, help_text='Material(s) of which the object is made', null=True, verbose_name='Material (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='object_type_nl',
            field=models.CharField(blank=True, help_text='Type of object', max_length=255, null=True, verbose_name='Object type (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_end_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period end (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Period (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='period_start_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period start (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='references_nl',
            field=models.TextField(blank=True, help_text='References to this object in the professional literature', null=True, verbose_name='References (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='site_found_nl',
            field=models.CharField(blank=True, help_text='Complete record of site where the object was found', max_length=255, null=True, verbose_name='Site found (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_nl',
            field=models.CharField(blank=True, help_text='Title of the object', max_length=255, null=True, verbose_name='Title (NL)'),
        ),
    ]
