# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 13:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0009_auto_20180430_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='', null=True, srid=4326, verbose_name='Geo coordinates'),
        ),
    ]
