# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0010_item_geo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='city',
        ),
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.AddField(
            model_name='item',
            name='city_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='city_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='country_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='country_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country (NL)'),
        ),
    ]
