# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0011_auto_20180502_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dynasty_orig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original dynasty'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_en',
            field=models.TextField(blank=True, null=True, verbose_name='Object date (EN)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_end_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object date end (EN)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_end_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object date end (NL)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_end_orig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original object date end'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Object date (NL)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Original object date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_start_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object date begin (EN)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_start_nl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object date begin (NL)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='period_start_orig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original object date begin'),
        ),
    ]
