# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0012_auto_20180506_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='period_orig',
            new_name='object_date_orig',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('importer_uid', 'record_number', 'inventory_number', 'api_url', 'web_url', 'title_orig', 'dimensions_orig', 'object_date_orig', 'object_type_orig', 'material_orig')]),
        ),
    ]
