# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0018_auto_20180506_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='period_end_en',
            new_name='object_date_end_en',
        ),
    ]
