# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


def copy_fields(apps, schema_editor):
    item_model = apps.get_model('muses_collection', 'Item')
    item_model.objects.update(period_orig=F('object_date_orig'))
    item_model.objects.update(period_en=F('object_date_en'))
    item_model.objects.update(period_nl=F('object_date_nl'))


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0022_auto_20180506_1523'),
    ]

    operations = [
        migrations.RunPython(
            copy_fields,
            reverse_code=migrations.RunPython.noop
        ),
    ]
