# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0023_item_period_data_migration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('importer_uid', 'record_number', 'inventory_number', 'api_url', 'web_url', 'title_orig', 'dimensions_orig', 'period_orig', 'object_date_begin_orig', 'object_date_end_orig', 'object_type_orig', 'material_orig')]),
        ),
    ]
