# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0025_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Dutch name'),
        ),
    ]
