# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0026_auto_20180509_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
