# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0027_auto_20180509_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nl', models.TextField(blank=True, null=True, verbose_name='Dutch name')),
                ('name_en', models.TextField(unique=True, verbose_name='English name')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='muses_collection.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
