# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0028_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='date_begin_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date begin (EN)'),
        ),
        migrations.AddField(
            model_name='period',
            name='date_end_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date end (EN)'),
        ),
    ]
