# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0030_auto_20180514_0830'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('importer_uid', 'record_number', 'inventory_number')]),
        ),
    ]
