# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 13:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0032_item_period_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='period_node',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The database period that is related to this object', null=True, on_delete=django.db.models.deletion.CASCADE, to='muses_collection.Period', verbose_name='Period tree node'),
        ),
    ]
