# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0033_auto_20180516_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classification_en',
            field=models.CharField(blank=True, help_text='Classification', max_length=255, null=True, verbose_name='Classification (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='classification_nl',
            field=models.CharField(blank=True, help_text='Classification', max_length=255, null=True, verbose_name='Classification (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='classification_orig',
            field=models.CharField(blank=True, help_text='Classification', max_length=255, null=True, verbose_name='Classification'),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords_en',
            field=models.TextField(blank=True, help_text='Keywords', null=True, verbose_name='Keywords (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords_nl',
            field=models.TextField(blank=True, help_text='Keywords', null=True, verbose_name='Keywords (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords_orig',
            field=models.TextField(blank=True, help_text='Keywords', null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='item',
            name='reign_en',
            field=models.CharField(blank=True, help_text='Reign', max_length=255, null=True, verbose_name='Reign (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='reign_nl',
            field=models.CharField(blank=True, help_text='Reign', max_length=255, null=True, verbose_name='Reign (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='reign_orig',
            field=models.CharField(blank=True, help_text='Reign', max_length=255, null=True, verbose_name='Reign'),
        ),
    ]
