# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0035_image_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classified_as',
            field=models.TextField(blank=True, help_text='How this object was classified by our AI.', null=True, verbose_name='Classified as'),
        ),
    ]
