# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0037_auto_20180710_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='image',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
