# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0039_auto_20180713_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='trimmed',
            field=models.BooleanField(default=False, verbose_name='Trimmed'),
        ),
    ]
