# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0040_image_trimmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dynasty_en',
            field=models.TextField(blank=True, null=True, verbose_name='Dynasty (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='dynasty_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Dynasty (NL)'),
        ),
    ]
