# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0041_auto_20180717_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accession_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accession date'),
        ),
        migrations.AddField(
            model_name='item',
            name='credit_line_en',
            field=models.TextField(blank=True, help_text='Credit line', null=True, verbose_name='Credit line (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='credit_line_nl',
            field=models.TextField(blank=True, help_text='Credit line', null=True, verbose_name='Credit line (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='credit_line_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Credit line'),
        ),
        migrations.AddField(
            model_name='item',
            name='culture_en',
            field=models.TextField(blank=True, help_text='Culture', null=True, verbose_name='Culture (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='culture_nl',
            field=models.TextField(blank=True, help_text='Culture', null=True, verbose_name='Culture (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='culture_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Culture'),
        ),
        migrations.AddField(
            model_name='item',
            name='excavation_en',
            field=models.TextField(blank=True, help_text='Excavation', null=True, verbose_name='Excavation (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='excavation_nl',
            field=models.TextField(blank=True, help_text='Excavation', null=True, verbose_name='Excavation (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='excavation_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Excavation'),
        ),
        migrations.AddField(
            model_name='item',
            name='exhibitions_en',
            field=models.TextField(blank=True, help_text='Exhibitions', null=True, verbose_name='Exhibitions (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='exhibitions_nl',
            field=models.TextField(blank=True, help_text='Exhibitions', null=True, verbose_name='Exhibitions (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='exhibitions_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Exhibitions'),
        ),
        migrations.AddField(
            model_name='item',
            name='inscriptions_en',
            field=models.TextField(blank=True, help_text='Inscriptions', null=True, verbose_name='Inscriptions (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='inscriptions_nl',
            field=models.TextField(blank=True, help_text='Inscriptions', null=True, verbose_name='Inscriptions (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='inscriptions_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Inscriptions'),
        ),
        migrations.AddField(
            model_name='item',
            name='locale_en',
            field=models.TextField(blank=True, help_text='Locale', null=True, verbose_name='Locale (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='locale_nl',
            field=models.TextField(blank=True, help_text='Locale', null=True, verbose_name='Locale (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='locale_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Locale'),
        ),
        migrations.AddField(
            model_name='item',
            name='museum_collection_en',
            field=models.TextField(blank=True, help_text='Museum collection', null=True, verbose_name='Museum collection (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='museum_collection_nl',
            field=models.TextField(blank=True, help_text='Museum collection', null=True, verbose_name='Museum collection (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='museum_collection_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='item',
            name='provenance_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Provenance'),
        ),
        migrations.AddField(
            model_name='item',
            name='region_en',
            field=models.TextField(blank=True, help_text='Region', null=True, verbose_name='Region (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='region_nl',
            field=models.TextField(blank=True, help_text='Region', null=True, verbose_name='Region (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='region_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='item',
            name='style_en',
            field=models.TextField(blank=True, help_text='Style', null=True, verbose_name='Style (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='style_nl',
            field=models.TextField(blank=True, help_text='Style', null=True, verbose_name='Style (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='style_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Style'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_region_en',
            field=models.TextField(blank=True, help_text='Sub region', null=True, verbose_name='Sub region (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_region_nl',
            field=models.TextField(blank=True, help_text='Sub region', null=True, verbose_name='Sub region (NL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_region_orig',
            field=models.TextField(blank=True, null=True, verbose_name='Sub region'),
        ),
    ]
