# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0042_auto_20180724_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='provenance_en',
            field=models.TextField(blank=True, help_text='Provenance', null=True, verbose_name='Provenance (EN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='provenance_nl',
            field=models.TextField(blank=True, help_text='Provenance', null=True, verbose_name='Provenance (NL)'),
        ),
    ]
