# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-22 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muses_collection', '0043_auto_20180730_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title of the object', max_length=500, null=True, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_nl',
            field=models.CharField(blank=True, help_text='Title of the object', max_length=500, null=True, verbose_name='Title (NL)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_orig',
            field=models.CharField(blank=True, help_text='Title of the object', max_length=500, null=True, verbose_name='Original title'),
        ),
    ]
