# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_priceoptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceOptions',
            new_name='People',
        ),
    ]
