# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20180619_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.People'),
        ),
    ]
