# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-29 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('cms', '0012_auto_20180625_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
