# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0017_exploreindexpage_explorepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymenOptionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('classname', models.CharField(blank=True, help_text='classname', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PaymenOptionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('options', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='explorepage',
            name='explore_title',
        ),
        migrations.AddField(
            model_name='exploreindexpage',
            name='anchor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exploreindexpage',
            name='background_color',
            field=models.CharField(blank=True, help_text='Background color in HEX (#000000)', max_length=255),
        ),
    ]
