# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_exploreindexpage_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploreindexpage',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='exploreindexpage',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='exploreindexpage',
            name='classname',
        ),
    ]
