# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-05 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20180705_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
    ]
