# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_auto_20180705_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieTextEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Cookie text EN',
            },
        ),
        migrations.CreateModel(
            name='CookieTextNL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Cookie text NL',
            },
        ),
    ]
