# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muses_collection', '0035_image_primary'),
        ('user_account', '0002_auto_20180607_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectionItemFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_item_favourites', to='muses_collection.Item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User collection item favourite',
                'verbose_name_plural': 'User collection item favourites',
            },
        ),
        migrations.AlterModelOptions(
            name='accountsettings',
            options={'verbose_name': 'Account setting', 'verbose_name_plural': 'Account settings'},
        ),
        migrations.AlterUniqueTogether(
            name='usercollectionitemfavourite',
            unique_together=set([('user', 'collection_item')]),
        ),
    ]
