# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20180618_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='unlimited_access',
            field=models.BooleanField(default=False, verbose_name='Unlimited access'),
        ),
    ]
