# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-20 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0004_accountsettings_unlimited_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date imported')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_search_images', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User search image',
                'verbose_name_plural': 'User search images',
            },
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usercollectionitemfavourite',
            name='collection_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_item_favourites', to='muses_collection.Item', verbose_name='Collection item'),
        ),
        migrations.AlterField(
            model_name='usercollectionitemfavourite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
