# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20180620_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchimage',
            name='image',
            field=models.ImageField(upload_to='user_uploads', verbose_name='Image'),
        ),
    ]
