# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_auto_20180625_0310'),
        ('user_account', '0006_auto_20180622_0823'),
    ]

    operations = [
    ]
