# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_merge_20180626_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='num_requests',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of requests'),
        ),
    ]
