# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0008_accountsettings_num_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='User group')),
                ('valid_from', models.DateField(verbose_name='Valid from')),
                ('valid_until', models.DateField(verbose_name='Valid until')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date imported')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('users', models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'User search image',
                'verbose_name_plural': 'User search images',
            },
        ),
    ]
