# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_usergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'User group', 'verbose_name_plural': 'User groups'},
        ),
    ]
