apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: aincient-nginx-mwhg5
  namespace: default
spec:
  clusterIP: 10.19.248.172
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-to-80-tcp
    nodePort: 32110
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-to-443-tcp
    nodePort: 31404
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 35.187.31.221