apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: aincient-nginx-staging-service
  namespace: default
  resourceVersion: "8332"
spec:
  clusterIP: 10.23.249.154
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-to-80-tcp
    nodePort: 31015
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-to-443-tcp
    nodePort: 30886
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 35.205.61.111
