# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(verbose_name='Original')),
                ('translated', models.TextField(blank=True, null=True, verbose_name='Translated')),
                ('source_language', models.CharField(max_length=255, verbose_name='Source language')),
                ('target_language', models.CharField(max_length=255, verbose_name='Target language')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([('original', 'source_language', 'target_language')]),
        ),
    ]
