# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='translated',
            new_name='translation',
        ),
    ]
