# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0003_auto_20180502_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geocoding',
            old_name='geolocation',
            new_name='geo_location',
        ),
    ]
