# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0004_auto_20180502_0836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([]),
        ),
    ]
