# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0006_add_unique_index_md5_20180502_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='original',
            field=models.TextField(verbose_name='Original'),
        ),
    ]
