# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0007_auto_20180502_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesauriTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(verbose_name='Original')),
                ('translation', models.TextField(blank=True, null=True, verbose_name='Translated')),
                ('source_language', models.CharField(max_length=255, verbose_name='Source language')),
                ('target_language', models.CharField(max_length=255, verbose_name='Target language')),
                ('translation_exists', models.BooleanField(default=False, verbose_name='Translation exists')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='thesauritranslate',
            unique_together=set([('original', 'source_language', 'target_language')]),
        ),
    ]
