# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0008_auto_20180507_0437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThesauriTranslate',
            new_name='ThesauriTranslation',
        ),
    ]
