# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0009_auto_20180507_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesauritranslation',
            name='supervised',
            field=models.BooleanField(default=False, verbose_name='Translation is supervised'),
        ),
    ]
