# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0010_thesauritranslation_supervised'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesauritranslation',
            name='disregard',
            field=models.BooleanField(default=False, verbose_name='Disregard the translation'),
        ),
    ]
