# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0011_thesauritranslation_disregard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(verbose_name='Original (wrong) translation')),
                ('replacement', models.TextField(blank=True, null=True, verbose_name='Fixed translation')),
                ('field', models.CharField(max_length=255, verbose_name='The field in which the faulty translation occurs')),
                ('exact_match', models.BooleanField(default=False, verbose_name='Should the match be exact?')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='translationfix',
            unique_together=set([('original', 'field')]),
        ),
    ]
