# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0012_auto_20180806_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationfix',
            name='exact_match',
            field=models.BooleanField(default=False, verbose_name='Match should be exact'),
        ),
        migrations.AlterField(
            model_name='translationfix',
            name='field',
            field=models.CharField(choices=[('name_en', 'name_en'), ('city_en', 'city_en'), ('country_en', 'country_en'), ('title_en', 'title_en'), ('description_en', 'description_en'), ('name_nl', 'name_nl'), ('city_nl', 'city_nl'), ('country_nl', 'country_nl'), ('title_nl', 'title_nl'), ('description_nl', 'description_nl')], max_length=255, verbose_name='The field in which the faulty translation occurs'),
        ),
    ]
