# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0013_auto_20180806_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationfix',
            options={'ordering': ['id'], 'verbose_name_plural': 'translation fixes'},
        ),
        migrations.AddField(
            model_name='translationfix',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Nederlands')], default='English', max_length=255, verbose_name='Language of the wrong translation'),
        ),
        migrations.AlterField(
            model_name='translationfix',
            name='field',
            field=models.CharField(choices=[('all', 'all'), ('name', 'name'), ('city', 'city'), ('country', 'country'), ('title', 'title'), ('description', 'description')], default='all', max_length=255, verbose_name='The field in which the faulty translation occurs'),
        ),
    ]
