# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached_api_calls', '0014_auto_20180806_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationfix',
            name='field',
            field=models.CharField(choices=[('all', 'all'), ('city', 'city'), ('country', 'country'), ('title', 'title'), ('description', 'description')], default='all', max_length=255, verbose_name='The field in which the faulty translation occurs'),
        ),
        migrations.AlterUniqueTogether(
            name='translationfix',
            unique_together=set([('original', 'field', 'language')]),
        ),
    ]
